chipset = "sdm845"

[bootimg]
base = 0x0
kernel = 0x8000
ramdisk = 0x1000000
second = 0
tags = 0x100
pagesize = 4096

[[device]]
vendor = "oneplus"
model = "enchilada"
append = ""
# append = "console=ttyMSM0,115200"

[[device]]
vendor = "oneplus"
model = "fajita"
append = ""
# append = "console=ttyMSM0,115200"

[[device]]
vendor = "shift"
model = "axolotl"
append = ""
# append = "console=ttyMSM0,115200"

[[device]]
vendor = "xiaomi"
model = "beryllium"
variant = "ebbg"
append = ""
# append = "console=ttyMSM0,115200"

[[device]]
vendor = "xiaomi"
model = "beryllium"
variant = "tianma"
append = ""
# append = "console=ttyMSM0,115200"

[[device]]
vendor = "xiaomi"
model = "polaris"
append = ""
# append = "console=ttyMSM0,115200"

[[device]]
vendor = "fairphone"
model = "fp4"
chipset = "sm7225"
append = "sdhci.debug_quirks=0x40"
